package com.cydeo.step_definitions;

import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class Login_StepDefinitions {


    @When("user enters librarian username")                         // autogenerated through run
    public void user_enters_librarian_username() {
    }


    @When("user enters librarian password")                         // autogenerated through run
    public void user_enters_librarian_password() {
    }


    @Then("user should see the dashboard")                          // autogenerated through run
    public void user_should_see_the_dashboard() {
    }


    @When("user enters student username")                           // generated with right click
    public void userEntersStudentUsername() {
    }


    @And("user enters student password")                            // generated with right click
    public void userEntersStudentPassword() {
    }


    @When("users enters admin username")                            // autogenerated through run
    public void users_enters_admin_username() {
        System.out.println("User enters admin username");
    }


    @When("user enters admin password")                             // autogenerated through run
    public void user_enters_admin_password() {
        System.out.println("User enters admin password");
    }


    @Given("user is on the library login page")
    public void userIsOnTheLibraryLoginPage() {
        System.out.println("User is on the library login page");
    }
}

